image: node:latest

stages:
    - deps
    - build

deps:
    stage: deps
    when: manual
    allow_failure: false
    only:
        - master
    cache: 
        key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
        paths:
        - node_modules/
    script:
        - npm ci
    only:
        changes:
        - package-lock.json

build:
    stage: build
    when: manual
    allow_failure: false
    only:
        - master
    cache: 
        key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
        paths:
        - node_modules/
        policy: pull
    script:
        - npx gulp build
    artifacts:
        expire_in: 1 day
        paths:
        - dist/
